### ISSUE TITLE
Valet & ___dist don't mix?

### ISSUE THREAD

**Issue by wihodges** [davidhellmann/generator-baukasten#52]
Just wondering how you serve the site? 

I typically use Valet and I see the localValet driver in the Craft install /___dist. Also the proxy localhost:8700 doesn't render as the root file is the valet link, not sure how that would even work without perhaps a new valet driver that looks for the subfolder. 

Project/boilerplate looks really interesting - Thanks!

**Comment by davidhellmann** [comment]
I go to the `___dist` and then I do `valet link sitename` and it works. Sorry for the delay.
